# Configure Hugo: https://gohugo.io/getting-started/configuration/#configuration-file
baseURL: https://cybmir.ru/
languageCode: en-us
title: Hugo ReFreshing Theme

enableInlineShortcodes:  true

Taxonomies:
  category:              "categories"
  tag:                   "tags"

# DefaultContentLanguage: en
DefaultContentLanguage: ru

languages:
  en:
    languageName:       English
    weight:             2
  ru:
    languageName:       Russian
    weight:             1
