# Configure Hugo: https://gohugo.io/getting-started/configuration/#configuration-file
# baseURL: "https://cybmir.ru/"
baseURL: "/"
languageCode: ru
title: Hugo-RFi-Cover

DefaultContentLanguage:  ru
# DefaultContentLanguage: en
disableLanguages: en

enableInlineShortcodes:  true
publishDir:              "@_site"
enableRobotsTXT:         false

# применяются относительные ссылки. Тo turn relative URLs into absolute use
# canonifyURLs: true.
canonifyURLs:            false

# bd5
markup:
  goldmark:
    renderer:
      unsafe:            true
  highlight:
    noClasses:           false
  tableOfContents:
    startLevel:          2
    endLevel:            4

params:
  logo: "/images/logo-cover.svg"
  title: Cover
  description: A one-page template for building simple and beautiful home pages.
  authors: "@mdo, wBuresh, Eric Fandor"
  site_version: 20210621rfi
  # option to specify the favicon image of the site
  # the path is relative to the folder "assetDir" of this configuration
  favicon: "/images/favicon.svg"

  darkMode: true
  # darkMode: false

  # parameter used to specify if you want to minify the imported js
  jsMinify: false
  # parameter used to specify if you want to minify the imported css
  cssMinify: false
  # parameter used to specify if you want to calculate the css integrity
  cssIntegrity: false
  # parameter used to specify if you want to calculate the js integrity
  jsIntegrity: false
  # option to specify the main colour of the theme
  # mainColour: "#F39200"
  # mainColour: "#00d1b2"
  mainColour: "#0d6efd"
  # mainColour: "#6c757d"


# homepage options
  homepage:
    # this options let you specify if you want a link to the homepage
    # it can be: "none", "menu", "footer" or "menu+footer"
    # linkPosition: "footer"
    # this options let you specify the text of the link to the homepage
    # linkText: "Homepage"
    # option to specify the title in the homepage
    title: Cover your page
    # option to specify the subtitle in the homepage
    subtitle: Cover is a one-page template for building simple and beautiful home pages.

## multi language support options
####################################
languages:
  en:
    languageName:       English
    weight:            2
    # title: In English
  ru:
    languageName:       Russian
    # title: На Русском
    weight:             1
      # Some sub-parameters of the "Homepage" and "footer" parameter

    params:
      homepage:
        title: Cover для вашего сайта
        subtitle: одностраничный шаблон для создания простой и красивой главной страницы.
