# Configure Hugo: https://gohugo.io/getting-started/configuration/#configuration-file
baseURL: https://cybmir.ru/
languageCode: en-us
title: Hugo ReFreshing Theme

enableInlineShortcodes:  true
publishDir:              "@_site"
enableRobotsTXT:         false

# применяются относительные ссылки. Тo turn relative URLs into absolute use # canonifyURLs: true.
canonifyURLs:            false

# bd5
markup:
  goldmark:
    renderer:
      unsafe:            true
  highlight:
    noClasses:           false
  tableOfContents:
    startLevel:          2
    endLevel:            4

DefaultContentLanguage:  ru
# DefaultContentLanguage: en

params:
  # option to specify the favicon image of the site
  # the path is relative to the folder "assetDir" of this configuration
  favicon: "/images/favicon-rfi.svg"
  # parameter used to specify if you want to minify the imported js
  jsMinify: false
  # parameter used to specify if you want to minify the imported css
  cssMinify: false
  # parameter used to specify if you want to calculate the css integrity
  cssIntegrity: false
  # parameter used to specify if you want to calculate the js integrity
  jsIntegrity: false
  # option to specify the main colour of the theme
  # mainColour: "#F39200"
  mainColour: "#00d1b2"





languages:
  en:
    languageName:       English
    weight:             2
  ru:
    languageName:       Russian
    weight:             1
